### ISSUE TITLE
Password Not Hash On Update

### ISSUE THREAD

**Issue by jmmalunao** [mattiamalonni/sequelize-bcrypt#1]
Created a standard user model/table and attached useBcrypt onto it.
Storing/creating new record works, even authenticating user at log-in.
But when updating the password field only, the new value was stored in plain not hash.

**Comment by mattiamalonni** [comment]
Solved in [#e39c6c6](https://github.com/mattiamalonni/sequelize-bcrypt/commit/e39c6c6c986f6480558a1fa26bd574e1c96b56e6)
